export default{
    First:'First',
    Second:'Second',
    Third:'Third',
    Login:'Login',
    Register:'Register',
    Forgot:'Forgot',
    Verify:'Verify',
    Bottom_Tab:'Bottom_Tab',
    Home:'Home',
    Message:'Message',
    Ads:'Ads',
    Profile:'Profile',
    Chats:'Chats',
    Hiring_Requests:'Hiring_Request',
    Categories:'Categories',
    Cooks:'Cooks',
    House_Cleaner:'House_Cleaner',
    Dusting:'Dusting',
    Laundry:'Laundry',
    Baby_Sitter:'Baby_Sitter',
    Patient_Care_Taker:'Patient_Care_Taker',
    All_In_One:'All_In_One',
    Maid_Details:'Maid_Details',
    CustomMaid:'CustomMaid',
    Chat:'Chat',
    Post_Ads:'Post_Ads',
    My_Wishlist:'My Wishlist',
    Hirring:'Hirring',
    Hirring_Details:'Hirring Details',
    My_Account:'My Account',
    Edit_Info:'Edit Info',
    Notification:'Notication',
    Language:'Language',
    App_Issues:'App_Issues',
    FAQ:'FAQ'
}